name: GMWF
description: "A dispensary management app (offline-first with Firebase)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI & utilities
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.12.0
  dropdown_button2: ^2.3.9
  another_flushbar: ^1.10.24
  fluttertoast: ^9.0.0
  printing: ^5.13.2
  screenshot: ^3.0.0

  # Networking & HTTP
  http: ^1.6.0
  connectivity_plus: ^7.0.0
  share_plus: ^12.0.1
  updater: ^0.2.5

  # State management & reactive
  rxdart: ^0.28.0
  provider: ^6.1.2
  uuid: ^4.5.2

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Misc
  crypto: ^3.0.7
  intl: ^0.20.2
  bitsdojo_window: ^0.1.6
  window_manager: ^0.5.1
  excel: ^4.0.6
  pdf: ^3.11.0

  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/gmwf-1.png"


flutter:
  uses-material-design: true

  fonts:
    - family: Noori
      fonts:
        - asset: assets/fonts/NooriNastaliq.ttf

  assets:
    - assets/icons/eye_close.png
    - assets/icons/eye_open.png
    - assets/logo/agmp.png
    - assets/logo/gmwf.jpg
    - assets/logo/gmwf.png
    - assets/logo/gmwf-1.png
    - assets/icons/WA.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/moon.png
    - assets/images/rx.png
    - assets/fonts/NooriNastaliq.ttf
